# Generated by Django 4.1 on 2023-01-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcpower',
            name='inventImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='dcpower/invent/', verbose_name='Фото инвентарного номера'),
        ),
        migrations.AlterField(
            model_name='dcpower',
            name='serialImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='dcpower/serial/', verbose_name='Фото серийного номера'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='inventImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='hdd/invent/', verbose_name='Фото инвентарного номера'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='serialImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='hdd/serial/', verbose_name='Фото серийного номера'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='inventImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='keyBoard/invent/', verbose_name='Фото инвентарного номера'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='serialImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='keyBoard/serial/', verbose_name='Фото серийного номера'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='inventImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='mouse/invent/', verbose_name='Фото инвентарного номера'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='serialImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='mouse/serial/', verbose_name='Фото серийного номера'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='inventImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='ram/invent/', verbose_name='Фото инвентарного номера'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='serialImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='ram/serial/', verbose_name='Фото серийного номера'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='inventImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='ssd/invent/', verbose_name='Фото инвентарного номера'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='serialImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='ssd/serial/', verbose_name='Фото серийного номера'),
        ),
    ]
