# Generated by Django 4.1 on 2023-01-12 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0001_initial'),
        ('workstation', '0002_alter_dcpower_inventimg_alter_dcpower_serialimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='ups',
            field=models.ForeignKey(blank=True, help_text='Укажите блок бесперебойного питания', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ups.ups', verbose_name='Блок бесперебойного питания'),
        ),
    ]
