# Generated by Django 4.1 on 2023-01-13 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0001_initial'),
        ('workstation', '0003_alter_workstation_ups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparty.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='dcpower',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparty.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparty.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparty.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparty.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparty.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparty.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparty.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparty.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparty.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparty.manufacturer', verbose_name='Производитель'),
        ),
    ]
