# Generated by Django 4.1 on 2023-01-13 04:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workstation', '0003_alter_workstation_ups'),
        ('employee', '0001_initial'),
        ('catalog', '0013_delete_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Введите номер ключа', max_length=50, null=True, verbose_name='Ключ')),
                ('licenseKeyFileOpen', models.FileField(blank=True, help_text='Прикрепите файл', null=True, upload_to='signature/Open/', verbose_name='Открытая часть лицензии')),
                ('licenseKeyFileClose', models.FileField(blank=True, help_text='Прикрепите файл', null=True, upload_to='signature/Close/', verbose_name='Закрытая часть лицензии')),
                ('periodOpen', models.DateField(blank=True, help_text='Укажите дату', null=True, verbose_name='Срок действия открытой части')),
                ('periodClose', models.DateField(blank=True, help_text='Укажите дату', null=True, verbose_name='Срок действия закрытой части')),
                ('employeeRegister', models.ForeignKey(blank=True, help_text='Укажите сотрудника', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='Сотрудник на которого оформлена ЭЦП')),
                ('employeeStorage', models.ForeignKey(blank=True, help_text='Укажите сотрудника', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employee.employee', verbose_name='Сотрудник у которого хранится ЭЦП')),
                ('storage', models.ForeignKey(blank=True, help_text='Укажите накопитель', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.storage', verbose_name='накопитель')),
                ('workstation', models.ForeignKey(blank=True, help_text='Укажите рабочую станцию', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workstation.workstation', verbose_name='Рабочая станция')),
            ],
            options={
                'verbose_name': 'ЭЦП',
                'verbose_name_plural': 'ЭЦП',
                'ordering': ['periodOpen', 'periodClose'],
            },
        ),
    ]
