# Generated by Django 4.1 on 2023-01-13 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0002_alter_accumulator_manufacturer_and_more'),
        ('signature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='storage',
            field=models.ForeignKey(blank=True, help_text='Укажите накопитель', null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumables.storage', verbose_name='накопитель'),
        ),
    ]
