repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: [--config, --write] # edit files in-place
        additional_dependencies:
          - prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.14.0
    hooks:
      - id: eslint
        types: [file]
        args: [--fix, --config, frontend/eslint.config.js]
        files: \.(js|ts|jsx)$
        additional_dependencies:
          - eslint
          - eslint-plugin-react
          - javascript
          - typescript
          - typescript-eslint
