default_stages: [pre-commit, push]
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: [--config, --write] # edit files in-place
        additional_dependencies:
          - prettier
          - prettier-plugin-svelte
          - svelte
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.14.0
    hooks:
      - id: eslint
        types: [file]
        args: [--fix, --config, frontend/eslint.config.js]
        files: \.(js|ts|svelte)$
        additional_dependencies:
          - eslint
          - eslint-plugin-svelte
          - svelte
          - typescript
          - typescript-eslint
