repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.24.0
    hooks:
      - id: eslint
        types: [file]
        args: [--fix, --config, frontend/eslint.config.js]
        files: \.(js|ts|jsx)$
        additional_dependencies:
          - eslint
          - eslint-plugin-react
          - javascript
          - typescript
          - typescript-eslint
