FROM node:16-alpine3.16 as build
WORKDIR /frontend
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm i axios reactstrap bootstrap
COPY ./public ./public
COPY ./src ./src
RUN npm run build


FROM nginx:stable-alpine
COPY --from=build ./frontend/build usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
CMD ["nginx", "-g", "daemon off;"]