default_stages: [pre-commit, pre-push]
repos:
  - repo: local
    hooks:
      - id: bakend
        name: run backend pre-commit
        language: system
        entry: bash -c 'cd backend && uv run pre-commit'
        pass_filenames: false
        types: [python]
        files: ^backend/
  - repo: local
    hooks:
      - id: frontend
        name: run front pre-commit
        language: system
        entry: bash -c 'cd frontend && npm run pre-commit'
        pass_filenames: false
        types: [javascript]
        files: ^frontend/
