version: "3.9"

services:
  web:
    build: ./myStockroom
    command: gunicorn myStockroom.wsgi:application --bind 0.0.0.0:8010 --timeout 120 --workers=3 --threads=3 --worker-connections=1000 # параметры сервера gunicorn
    restart: always
    volumes:
      - ./myStockroom:/myStockroom
      - .myStockroom/static:/home/myStockroom/web/static
      - .myStockroom/media:/home/myStockroom/web/mediafiles 
    expose:
      - 8010
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_PASSWORD=${SQL_PASSWORD} 

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: adminDevelop
      POSTGRES_PASSWORD: zx23SA21
      POSTGRES_DB: buildAndTech
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./database/Init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database:/var/lib/postgresql/data

  nginx:
    build: ./reactfrontendapp
    restart: always
    volumes:
      - ./myStockroom/static:/home/myStockroom/web/static
      - ./myStockroom/media:/home/myStockroom/web/mediafiles 
    ports:
      - 80:80
    depends_on:
      - web

  redis:
    image: redis:alpine
    restart: always

  celery:
    restart: always
    build:
      context: ./myStockroom
    command: celery -A myStockroom worker -l info
    volumes:
      - ./myStockroom:/myStockroom
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web

  celery-beat:
    build: ./myStockroom
    command: celery -A myStockroom beat -l info
    restart: always
    volumes:
      - ./myStockroom:/myStockroom
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  flower:
    build: ./myStockroom
    command: celery -A myStockroom flower --port=5555 --broker=redis://redis:6379/0
    volumes:
      - ./myStockroom:/myStockroom
    env_file:
      - ./.env.dev
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

  pgadmin:
    image: dpage/pgadmin4:6.14
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.db
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"



     
volumes:
  pgadmin-data:  
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./pgadmin-data/_data

  
   