version: "3.9"

services:
  web:
    build: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8010 --timeout 120 --workers=3 --threads=3 --worker-connections=1000 # параметры сервера gunicorn
    restart: always
    volumes:
      - ./backend:/backend
      - ./static:/home/backend/web/static
      - ./media:/home/backend/web/mediafiles
    ports:
      - "8010:8010"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis


  db:
    image: postgres:14
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./database/Init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database:/var/lib/postgresql/data

  nginx:
    build: ./frontend
    restart: always
    command: npm start
    volumes:
      - ./static:/home/backend/web/static
      - ./media:/home/backend/web/mediafiles
    ports:
      - "3000:3000"
    depends_on:
      - web

  redis:
    image: redis:alpine
    restart: always

  celery:
    restart: always
    build:
      context: ./backend
    command: celery -A backend worker -l info
    volumes:
      - ./backend:/backend
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

  celery-beat:
    build: ./backend
    command: celery -A backend beat -l info
    restart: always
    volumes:
      - ./backend:/backend
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  flower:
    build: ./backend
    command: celery -A backend flower --port=5555 --broker=redis://redis:6379/0
    volumes:
      - ./backend:/backend
    env_file:
      - ./.env
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db


