# Файл docker-compose должен начинаться с тега версии.
# Мы используем "3" так как это - самая свежая версия на момент написания этого кода.

version: "3.9"

# Следует учитывать, что docker-composes работает с сервисами.
# 1 сервис = 1 контейнер.
# Сервисом может быть клиент, сервер, сервер баз данных...
# Раздел, в котором будут описаны сервисы, начинается с 'services'.

services:
  web:
    build: ./
    command: gunicorn locallibrary.wsgi:application --bind 0.0.0.0:8010 --timeout 120 --workers=3 --threads=3 --worker-connections=1000 # параметры сервера gunicorn
    restart: always
    volumes:
      - ./:/myBase
      - ./static:/home/mybase/web/static
      - ./media:/home/mybase/web/mediafiles #проброс папки с файлами
    expose:
      - 8010
    env_file:
      - ./.env.dev
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=${SQL_PASSWORD} 
  db:
    image: postgres:14
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=adminDevelop
      - POSTGRES_PASSWORD=zx23SA21
      - POSTGRES_DB=buildAndTech
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./static:/home/mybase/web/static
      - ./media:/home/mybase/web/mediafiles #проброс папки с файлами
    ports:
      - 80:80
    depends_on:
      - web
  pgadmin:
    image: dpage/pgadmin4:6.14
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: makarovskiynv@adm.lbt.yanao.ru
      PGADMIN_DEFAULT_PASSWORD: zx23SA21
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"



     
volumes:
  pgadmin-data:  

  
   