services:
  web:
    build: ./backend
    hostname: backend
    container_name: backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8010 --timeout 120 --workers=3 --threads=3 --worker-connections=1000 # параметры сервера gunicorn
    restart: always
    volumes:
      - ./backend/src:/backend/src
      - ./backend/src/static:/home/backend/web/static
      - ./backend/src/media:/home/backend/web/mediafiles
    ports:
      - "8010:8010"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  react:
    build:
      context: ./frontend
    hostname: frontend
    container_name: frontend
    volumes:
      - ./frontend:/frontend
      - ./backend/src/static:/home/backend/web/static
      - ./backend/src/media:/home/backend/web/mediafiles
      - /frontend/node_modules
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - web

  db:
    container_name: db
    image: postgres:14
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./database/Init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database:/var/lib/postgresql/data

  angie:
    build: ./angie
    restart: always
    hostname: stock
    container_name: nginx
    volumes:
      - ./frontend:/frontend
      - ./backend/src/static:/home/backend/web/static
      - ./backend/src/media:/home/backend/web/mediafiles
    ports:
      - "80:80"
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: redis
    container_name: redis
    restart: always

  celery:
    restart: always
    container_name: celery
    build:
      context: ./backend
      target: dev
    command: uv run celery -A backend worker -l info
    volumes:
      - ./backend/src:/backend/src
    env_file:
      - ./.env
    depends_on:
      - backend

  celery-beat:
    build: ./backend
    command: celery -A backend beat -l info
    container_name: celery-beat
    restart: always
    volumes:
      - ./backend/src:/backend/src
    env_file:
      - ./.env
    depends_on:
      - celery

  flower:
    build: ./backend
    command: celery -A backend flower --port=5555 --broker=redis://redis:6379/0
    container_name: flower
    volumes:
      - ./backend/src:/backend/src
    env_file:
      - ./.env
    ports:
      - "5557:5555"
    depends_on:
      - redis
      - db
      - celery
