services:
  backend:
    build:
      context: ./
      target: dev
    hostname: backend
    image: backend
    container_name: backend
    command: uv run gunicorn backend.wsgi:application --bind 0.0.0.0:8010 --timeout 120 --workers=3 --threads=3 --worker-connections=1000 # параметры сервера gunicorn
    restart: always
    volumes:
      - ./src:/backend/src
      - ./site:/backend/site
      - ../public:/public
      - ./src/static:/home/backend/web/static
      - ./src/media:/home/backend/web/mediafiles
    expose:
      - 8010
    env_file:
      - ./.env
    depends_on:
      - db
      - redis


  db:
    image: postgres:14
    container_name: db
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./database/Init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    hostname: stock
    container_name: nginx
    restart: always
    volumes:
      - ./src/static:/home/backend/web/static
      - ./src/media:/home/backend/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  celery:
    restart: always
    image: backend
    container_name: celery
    build:
      context: ./
      target: dev
    command: uv run celery -A backend worker -l info
    volumes:
      - ./src/:/backend/src/
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - backend

  celery-beat:
    image: backend
    build:
      context: ./
      target: dev
    command: uv run celery -A backend beat -l info
    container_name: celery-beat
    restart: always
    volumes:
      - ./src:/backend/src
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  flower:
    image: backend
    build:
      context: ./
      target: dev
    command: uv run celery -A backend flower --port=5555 --broker=redis://redis:6379/0
    container_name: flower

    volumes:
      - ./src:/backend/src
    env_file:
      - ./.env
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db
