ARG PYTHON_BASE=3.12-slim-bookworm
# build stage
FROM python:$PYTHON_BASE AS builder

# install uv
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates
ADD https://astral.sh/uv/install.sh /uv-installer.sh
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"

# set work directory
WORKDIR /backend/src
# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
COPY ../pyproject.toml ../uv.lock ../README.md ../.dockerignore ../entrypoint.sh ../LICENSE ../
RUN cd ..
RUN uv lock

# run dev stage
FROM builder AS dev
RUN cd ..
# retrieve packages from build stage
#COPY --from=ghcr.io/astral-sh/uv:0.5.0 /uv /uvx /bin/
RUN uv sync
COPY ../src /backend/src
COPY ../docs /backend/docs
COPY ../mkdocs.yml /backend/mkdocs.yml
ENTRYPOINT ["/backend/entrypoint.sh" ]


# run prod stage
FROM builder AS prod


COPY ../src /backend/src

ENTRYPOINT ["/backend/entrypoint.sh" ]
