ARG PYTHON_BASE=3.12-slim
# build stage
FROM python:$PYTHON_BASE AS builder
# build base image
RUN pip install -U pdm
ENV PDM_CHECK_UODATE=false
# set work directory
WORKDIR /backend/src
# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
# install psycopg2 dependencies
RUN apt-get update \
    && apt-get install -y postgresql-server-dev-all gcc python3-dev musl-dev
COPY ../pyproject.toml ../pdm.lock ../README.md ../.dockerignore ../entrypoint.sh ../LICENSE ../
RUN cd ..
RUN pdm lock

# run dev stage
FROM builder AS dev
# add git folder for isort check
COPY ../.env .env
RUN cd ..
# retrieve packages from build stage
#COPY --from=builder /backend/.venv /backend/.venv
RUN pdm install --check --dev

ENV PATH="/backend/.venv/bin:$PATH"
ENTRYPOINT ["/backend/entrypoint.sh" ]


# run prod stage
FROM builder AS prod

# retrieve packages from build stage
COPY --from=builder /backend/.venv /backend/.venv
RUN pdm install --check --prod --no-editable
COPY ./src /backend/src

ENV PATH="/backend/.venv/bin:$PATH"
ENTRYPOINT ["/backend/entrypoint.sh" ]
