[project]
name = "stockroom"
version = "0.8.0"
description = "The project is designed to maintain a database with equipment and consumables"
authors = [
    {name = "Makarovskiy Nikolay", email = "adrameleh666@gmail.com"},
]
requires-python = ">=3.13"
readme = "README.md"
license = {file = "LICENSE"}

dependencies = [
    "asgiref >=3.8.1",
    "attrs >=25.3.0",
    "celery >=5.5.3",
    "diff-match-patch >=20241021",
    "Django >=5.2.3",
    "django-adaptors >=0.2.5",
    "django-appconf >=1.1.0",
    "django-celery-beat >=2.8.1",
    "django-cors-headers >=4.7.0",
    "django-filter >=25.1",
    "django-import-export >=4.3.8",
    "djangorestframework >=3.16.0",
    "djangorestframework-simplejwt >=5.5.0",
    "flower >=2.0.1",
    "gunicorn >=23.0.0",
    "hiredis >=3.2.1",
    "markdown >=3.8.2",
    "Pillow >=11.2.0",
    "psycopg[binary,pool] >=3.2.9",
    "python-dateutil >=2.9.post0",
    "pytz >=2025.2",
    "redis >=6.2.0",
    "setuptools >=80.9.0",
    "six >=1.17.0",
    "sqlparse >=0.5.3",
    "tablib[all] >=3.8.0",
]

[dependency-groups]
docs = [
    "mkdocs >=1.6.1",
    "mkdocs-material >=9.6.14",
    "mkdocstrings[python] >=0.29.1",
]
lint = [
    "celery-types >=0.23.0",
    "django-stubs >=5.2.1",
    "djangorestframework-stubs >=3.16.0",
    "mypy >=1.16.1",
    "pre-commit >=4.2.0",
    "ruff >=0.11.8",
]
test = [
    "junitxml >=0.7",
    "pytest >=8.4.1",
    "pytest-cov >=6.2.1",
    "pytest-django >=4.11.1",
    "pytest-xdist >=3.7.0",
    ]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/"]

[tool.uv]
default-groups = []

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py313"
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "__pycache__",
]


[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.mypy]
mypy_path = "./backend"
follow_imports = "silent"
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
show_error_codes = true
warn_unused_ignores = false
show_error_context = true
disable_error_code = "annotation-unchecked"
exclude = [
    '^pyproject.toml$',
]
plugins = [
    "mypy_django_plugin.main",
    "mypy_drf_plugin.main",
]

[mypy-pyproj]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "import_export.*",
    "rest_framework.*",
    ]
ignore_missing_imports = true


[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "./backend"

[tool.django-stubs]
django_settings_module = "backend.settings.production"
