# Generated by Django 4.1 on 2023-01-12 11:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_remove_accumulator_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='toner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название модели', max_length=50, verbose_name='Модель')),
                ('buhCode', models.CharField(help_text='Введите код по бухгалтерии', max_length=50, verbose_name='Код в бухгалтерии')),
                ('score', models.IntegerField(blank=True, help_text='Введите количество на складе', null=True, verbose_name='Остаток на складе')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Тонер',
                'verbose_name_plural': 'Тонеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='fotoval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название модели', max_length=50, verbose_name='Модель')),
                ('buhCode', models.CharField(help_text='Введите код по бухгалтерии', max_length=50, verbose_name='Код в бухгалтерии')),
                ('mileage', models.IntegerField(blank=True, help_text='Введите пробег', null=True, verbose_name='Пробег')),
                ('score', models.IntegerField(blank=True, help_text='Введите количество на складе', null=True, verbose_name='Остаток на складе')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Фотовал',
                'verbose_name_plural': 'Фотовалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='cartridge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название модели', max_length=50, verbose_name='Модель')),
                ('buhCode', models.CharField(help_text='Введите код по бухгалтерии', max_length=50, verbose_name='Код в бухгалтерии')),
                ('score', models.IntegerField(blank=True, help_text='Введите количество на складе', null=True, verbose_name='Остаток на складе')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': 'Картриджы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='accumulator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название модели', max_length=50, verbose_name='Модель')),
                ('power', models.CharField(blank=True, help_text='Укажите мощность', max_length=50, null=True, verbose_name='Мощность')),
                ('voltage', models.CharField(blank=True, help_text='Укажите напряжение', max_length=50, null=True, verbose_name='Напряжение')),
                ('current', models.CharField(blank=True, help_text='Укажите ток', max_length=50, null=True, verbose_name='Ток')),
                ('score', models.IntegerField(blank=True, help_text='Введите количество на складе', null=True, verbose_name='Остаток на складе')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Аккумулятор',
                'verbose_name_plural': 'Аккумуляторы',
                'ordering': ['name'],
            },
        ),
    ]
