# Generated by Django 4.1 on 2023-01-13 05:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('counterparty', '0001_initial'),
        ('consumables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accumulator',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparty.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparty.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='fotoval',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparty.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='toner',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparty.manufacturer', verbose_name='Производитель'),
        ),
        migrations.CreateModel(
            name='storage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название', max_length=50, verbose_name='Название')),
                ('modelStorage', models.CharField(blank=True, help_text='Введите название модели', max_length=200, null=True, verbose_name='Модель')),
                ('serial', models.CharField(blank=True, help_text='Введите серийный номер', max_length=50, null=True, verbose_name='Серийный номер')),
                ('serialImg', models.ImageField(blank=True, help_text='Прикрепите файл', null=True, upload_to='storage/serial/', verbose_name='Фото серийного номера')),
                ('invent', models.CharField(blank=True, help_text='Введите инвентаризационный номер', max_length=50, null=True, verbose_name='Инвентарный номер')),
                ('inventImg', models.ImageField(blank=True, help_text='Прикрепите файл', null=True, upload_to='storage/invent/', verbose_name='Фото инвентарного номера')),
                ('plug', models.TextField(blank=True, help_text='Укажите тип подключения', max_length=20, null=True, verbose_name='Тип подключения')),
                ('typeMemory', models.TextField(blank=True, help_text='Укажите тип памяти', max_length=200, null=True, verbose_name='Тип памяти')),
                ('volumeMemory', models.TextField(blank=True, help_text='Укажите объем памяти', max_length=200, null=True, verbose_name='Объем памяти')),
                ('employee', models.ForeignKey(blank=True, help_text='Укажите сотрудника', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='Сотрудник')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparty.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Накопитель',
                'verbose_name_plural': 'Накопители',
                'ordering': ['employee', 'name'],
            },
        ),
    ]
