# Generated by Django 4.1 on 2023-01-12 12:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0010_delete_printer'),
        ('consumables', '0001_initial'),
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='printer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Введите название принтера', max_length=50, null=True, verbose_name='Название')),
                ('modelPrinter', models.CharField(blank=True, help_text='Введите модель принтера', max_length=50, null=True, verbose_name='Модель')),
                ('serial', models.CharField(blank=True, help_text='Введите серийный номер', max_length=50, null=True, verbose_name='Серийный номер')),
                ('serialImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='printer/serial/', verbose_name='Фото серийного номера')),
                ('invent', models.CharField(blank=True, help_text='Введите инвентарный номер', max_length=50, null=True, verbose_name='Инвентарный номер')),
                ('inventImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='printer/invent/', verbose_name='Фото инвентарного номера')),
                ('usbPort', models.TextField(blank=True, help_text='Введите количество и тип', max_length=200, null=True, verbose_name='USB')),
                ('lanPort', models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True, verbose_name='LAN')),
                ('tray1', models.TextField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2'), ('A1', 'A1'), ('A0', 'A0'), ('A5', 'A5'), ('Конверт', 'Конверт'), ('Отсутствует', 'Отсутствует')], default='A4', help_text='Укажите формат бумаги', max_length=15, verbose_name='Лоток №1 для подачи бумаги')),
                ('tray2', models.TextField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2'), ('A1', 'A1'), ('A0', 'A0'), ('A5', 'A5'), ('Конверт', 'Конверт'), ('Отсутствует', 'Отсутствует')], default='A3', help_text='Укажите формат бумаги', max_length=15, verbose_name='Лоток №2 для подачи бумаги')),
                ('tray3', models.TextField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2'), ('A1', 'A1'), ('A0', 'A0'), ('A5', 'A5'), ('Конверт', 'Конверт'), ('Отсутствует', 'Отсутствует')], default='Отсутствует', help_text='Укажите формат бумаги', max_length=15, verbose_name='Лоток №3 для подачи бумаги')),
                ('traySide', models.TextField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2'), ('A1', 'A1'), ('A0', 'A0'), ('A5', 'A5'), ('Конверт', 'Конверт'), ('Отсутствует', 'Отсутствует')], default='A4', help_text='Укажите формат бумаги', max_length=15, verbose_name='Боковой лоток для подачи бумаги')),
                ('score', models.IntegerField(blank=True, help_text='Введите количество на складе', null=True, verbose_name='Остаток на складе')),
                ('cartridge', models.ForeignKey(blank=True, help_text='Укажите картридж', null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumables.cartridge', verbose_name='Картридж')),
                ('fotoval', models.ForeignKey(blank=True, help_text='Укажите фотовал', null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumables.fotoval', verbose_name='Фотовал')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель')),
                ('toner', models.ForeignKey(blank=True, help_text='Укажите тонер', null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumables.toner', verbose_name='Тонер')),
                ('workplace', models.ForeignKey(blank=True, help_text='Укажите рабочее место', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workplace.workplace', verbose_name='Рабочее место')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
                'ordering': ['name'],
            },
        ),
    ]
