# Generated by Django 4.1 on 2023-01-11 09:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='departament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название отдела', max_length=50, verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите должность', max_length=50, verbose_name='Должность')),
                ('departament', models.ForeignKey(blank=True, help_text='Введите название отдела', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.departament', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Введите имя сотрудника', max_length=50, verbose_name='Имя сотрудника')),
                ('sername', models.CharField(blank=True, help_text='Введите отчество сотрудника', max_length=50, verbose_name='Отчество сотрудника')),
                ('family', models.CharField(blank=True, help_text='Введите фамилию сотрудника', max_length=50, verbose_name='Фамилия сотрудника')),
                ('employeeEmail', models.EmailField(blank=True, help_text='Введие e-mail', max_length=254, null=True, unique=True, verbose_name='e-mail')),
                ('post', models.ForeignKey(blank=True, help_text='Выберете должность', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.post', verbose_name='Должность')),
                ('workplace', models.ForeignKey(blank=True, help_text='Выберете рабочее место', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workplace.workplace', verbose_name='Рабочее место')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['name', '-workplace'],
            },
        ),
    ]
