# Generated by Django 4.1 on 2023-01-13 05:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите наименование производителя', max_length=150, verbose_name='Производитель')),
                ('country', models.CharField(help_text='Введите название страны', max_length=150, verbose_name='Страна')),
                ('production', models.CharField(help_text='Введите страну производства', max_length=150, verbose_name='Страна производства')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
            },
        ),
    ]
