# Generated by Django 4.0.6 on 2022-10-26 05:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartridge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название модели', max_length=50, verbose_name='Модель')),
                ('manufactured', models.CharField(blank=True, help_text='Введите название производителя', max_length=50, null=True, verbose_name='Производитель')),
                ('serial', models.CharField(blank=True, help_text='Введите серийный номер', max_length=50, null=True, verbose_name='Серийный номер')),
                ('serialImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='printer/cartridge/', verbose_name='Серийный номер')),
                ('buhCode', models.CharField(help_text='Введите код по бухгалтерии', max_length=50, verbose_name='Код в бухгалтерии')),
                ('score', models.IntegerField(blank=True, help_text='Введите количество на складе', null=True, verbose_name='Остаток на складе')),
            ],
            options={
                'verbose_name_plural': 'картридж',
            },
        ),
        migrations.CreateModel(
            name='departament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название отдела', max_length=50, verbose_name='Отдел')),
            ],
            options={
                'verbose_name_plural': 'Отдел',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Введите имя сотрудника', max_length=50, verbose_name='Имя сотрудника')),
                ('sername', models.CharField(blank=True, help_text='Введите отчество сотрудника', max_length=50, verbose_name='Отчество сотрудника')),
                ('family', models.CharField(blank=True, help_text='Введите фамилию сотрудника', max_length=50, verbose_name='Фамилия сотрудника')),
                ('employeeEmail', models.EmailField(blank=True, help_text='Введие e-mail', max_length=254, null=True, unique=True, verbose_name='e-mail')),
            ],
            options={
                'verbose_name_plural': 'Сотрудник',
                'ordering': ['name', '-workplace'],
            },
        ),
        migrations.CreateModel(
            name='manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите наименование производителя', max_length=150, verbose_name='Производитель')),
                ('country', models.CharField(help_text='Введите название страны', max_length=150, verbose_name='Страна')),
                ('production', models.CharField(help_text='Введите страну производства', max_length=150, verbose_name='Страна производства')),
            ],
            options={
                'verbose_name_plural': 'Производитель',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='monitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите Название модели', max_length=50, verbose_name='Модель')),
                ('manufacturer', models.CharField(blank=True, help_text='Введите Название производителя', max_length=50, null=True, verbose_name='Производитель')),
                ('serial', models.CharField(blank=True, help_text='Введите серийный номер', max_length=50, null=True)),
                ('serialImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='monitor/serial/')),
                ('invent', models.CharField(blank=True, help_text='Введите инвентаризационный номер', max_length=50, null=True)),
                ('inventImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='monitor/invent/')),
            ],
            options={
                'verbose_name_plural': 'Монитор',
            },
        ),
        migrations.CreateModel(
            name='motherboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите Название модели', max_length=50)),
                ('manufacturer', models.CharField(blank=True, help_text='Введите Название производителя', max_length=50, null=True, verbose_name='Производитель')),
                ('serial', models.CharField(blank=True, help_text='Введите серийный номер', max_length=50, null=True)),
                ('serialImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='motherboard/')),
                ('invent', models.CharField(blank=True, help_text='Введите серийный номер', max_length=50, null=True)),
                ('inventImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='motherboard/')),
                ('CPUSoket', models.TextField(blank=True, help_text='Описание сокета', max_length=200, null=True, verbose_name='CPU Soket')),
                ('RAMSlot', models.TextField(blank=True, help_text='Описание RAM', max_length=200, null=True, verbose_name='RAM Slot')),
                ('USBPort', models.TextField(blank=True, help_text='Введите количество и тип', max_length=200, null=True, verbose_name='USB Port')),
                ('COMPort', models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True, verbose_name='COM Port')),
                ('PCI_E', models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True, verbose_name='PCI Express')),
                ('PCI', models.TextField(blank=True, help_text='Введите количество и тип', max_length=200, null=True, verbose_name='PCI')),
                ('VGA', models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True)),
                ('SATA', models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True)),
                ('HDMI', models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True)),
                ('DispayPort', models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True)),
                ('powerSupply', models.TextField(blank=True, help_text='Введите конфигурацию', max_length=200, null=True, verbose_name='Питание материнской платы')),
                ('powerSupplyCPU', models.TextField(blank=True, help_text='Введите конфигурацию', max_length=200, null=True, verbose_name='Питание CPU')),
            ],
            options={
                'verbose_name_plural': 'Материнская плата',
            },
        ),
        migrations.CreateModel(
            name='os',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название ОС', max_length=50, verbose_name='Операционная система')),
                ('version', models.CharField(blank=True, help_text='Укажите версию', max_length=200, null=True, verbose_name='Версия')),
                ('bitDepth', models.CharField(blank=True, help_text='Укажите разрядность', max_length=200, null=True, verbose_name='разрядность')),
                ('licenseKeyText', models.CharField(blank=True, help_text='Введите лицензтонный ключ', max_length=50, null=True, verbose_name='Введите ключ')),
                ('licenseKeyImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='OS/', verbose_name='Фото ключа')),
                ('licenseKeyFile', models.FileField(blank=True, help_text='прикрепите файл', null=True, upload_to='OS/', verbose_name='Файл лицензии')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name_plural': 'ОС',
            },
        ),
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название модели', max_length=50, verbose_name='Название')),
                ('manufactured', models.CharField(blank=True, help_text='Введите название производителя', max_length=50, null=True, verbose_name='Производитель')),
                ('paperFormat', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2'), ('A1', 'A1'), ('A0', 'A0'), ('A5', 'A5')], default='A4', help_text='Укажите формат', max_length=5, verbose_name='Формат')),
                ('score', models.IntegerField(blank=True, help_text='Введите количество на складе', null=True, verbose_name='Остаток на складе')),
            ],
            options={
                'verbose_name_plural': 'Бумага',
            },
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Введите номер кабинета', max_length=15, verbose_name='Кабинет')),
                ('building', models.CharField(blank=True, help_text='Введите название здания', max_length=25, verbose_name='Здание')),
                ('floor', models.CharField(blank=True, help_text='Введите номер этажа', max_length=25, verbose_name='Этаж')),
            ],
            options={
                'verbose_name_plural': 'Кабинет',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='workplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False, verbose_name='Введите уникальный UUID4)')),
                ('name', models.CharField(help_text='Введите номер рабочего места', max_length=50, verbose_name='Рабочее место')),
                ('room', models.ForeignKey(blank=True, help_text='Выберете номер кабинета', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.room', verbose_name='Номер кабинета')),
            ],
            options={
                'verbose_name_plural': 'Рабочее место',
                'ordering': ['room'],
            },
        ),
        migrations.CreateModel(
            name='workstation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите номер станции', max_length=50, verbose_name='Рабочая станция')),
                ('modelComputer', models.CharField(blank=True, help_text='Введите название модели', max_length=200, null=True, verbose_name='Модель')),
                ('serial', models.CharField(blank=True, help_text='Введите серийный номер', max_length=50, null=True, verbose_name='Серийный номер')),
                ('serialImg', models.ImageField(blank=True, help_text='Прикрепите файл', null=True, upload_to='workstation/serial/', verbose_name='Фото серийного номера')),
                ('invent', models.CharField(blank=True, help_text='Введите инвентаризационный номер', max_length=50, null=True, verbose_name='Инвентарный номер')),
                ('inventImg', models.ImageField(blank=True, help_text='Прикрепите файл', null=True, upload_to='workstation/invent/', verbose_name='Фото инвентарного номера')),
                ('cpu', models.TextField(blank=True, help_text='Укажите CPU', max_length=200, null=True, verbose_name='CPU')),
                ('gpu', models.TextField(blank=True, help_text='Укажите GPU', max_length=200, null=True, verbose_name='GPU')),
                ('ram', models.TextField(blank=True, help_text='Укажите RAM', max_length=200, null=True, verbose_name='RAM')),
                ('ssd', models.TextField(blank=True, help_text='Укажите SSD', max_length=200, null=True, verbose_name='SSD')),
                ('hdd', models.TextField(blank=True, help_text='Укажите HDD', max_length=200, null=True, verbose_name='HDD')),
                ('dcpower', models.TextField(blank=True, help_text='Укажите блок питания', max_length=200, null=True, verbose_name='Блок питания')),
                ('keyBoard', models.TextField(blank=True, help_text='Укажите клавиатуру', max_length=200, null=True, verbose_name='Клавиатура')),
                ('mouse', models.TextField(blank=True, help_text='Укажите мышь', max_length=200, null=True, verbose_name='Мышь')),
                ('ups', models.TextField(blank=True, help_text='Укажите блок бесперебойного питания', max_length=200, null=True, verbose_name='Блок бесперебойного питания')),
                ('employee', models.ForeignKey(blank=True, help_text='Укажите блок бесперебойного питания', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.employee', verbose_name='Блок бесперебойного питания')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель')),
                ('monitor', models.ForeignKey(blank=True, help_text='Укажите монитор', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.monitor', verbose_name='Монитор')),
                ('motherboard', models.ForeignKey(blank=True, help_text='Укажите материнскую плату', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.motherboard', verbose_name='Материнская плата')),
                ('os', models.ForeignKey(blank=True, help_text='Укажите ОС', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.os', verbose_name='Операционная система')),
                ('workplace', models.ForeignKey(blank=True, help_text='Укажите рабочее место', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.workplace', verbose_name='Рабочее место')),
            ],
            options={
                'verbose_name_plural': 'Рабочая станция',
                'ordering': ['employee', 'name', 'workplace'],
            },
        ),
        migrations.CreateModel(
            name='software',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название ПО', max_length=50, verbose_name='Програмное обеспечение')),
                ('version', models.CharField(blank=True, help_text='Укажите версию', max_length=200, null=True, verbose_name='Версия')),
                ('bitDepth', models.CharField(blank=True, help_text='Укажите разрядность', max_length=200, null=True, verbose_name='разрядность')),
                ('licenseKeyText', models.CharField(blank=True, help_text='Введите лицензтонный ключ', max_length=50, null=True, verbose_name='Введите ключ')),
                ('licenseKeyImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='soft/', verbose_name='Фото ключа')),
                ('licenseKeyFile', models.FileField(blank=True, help_text='прикрепите файл', null=True, upload_to='soft/', verbose_name='Файл лицензии')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель')),
                ('workstation', models.ForeignKey(blank=True, help_text='Укажите рабочую станцию', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.workstation', verbose_name='Рабочая станция')),
            ],
            options={
                'verbose_name_plural': 'ПО',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='printer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название модели', max_length=50, verbose_name='Модель')),
                ('manufactured', models.CharField(blank=True, help_text='Введите название производителя', max_length=50, null=True, verbose_name='Производитель')),
                ('serial', models.CharField(blank=True, help_text='Введите серийный номер', max_length=50, null=True, verbose_name='Серийный номер')),
                ('serialImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='motherboard/soft/', verbose_name='Серийный номер')),
                ('invent', models.CharField(blank=True, help_text='Введите инвентаризационный номер', max_length=50, null=True, verbose_name='Инвентарный номер')),
                ('inventImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='workstation/invent/', verbose_name='Инвентарный номер')),
                ('USBPort', models.TextField(blank=True, help_text='Введите количество и тип', max_length=200, null=True, verbose_name='USB')),
                ('LANPort', models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True, verbose_name='LAN')),
                ('cartridge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cartridge', verbose_name='Картридж')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.employee', verbose_name='Сотрудник')),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.paper', verbose_name='Бумага')),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.workplace', verbose_name='Рабочее место')),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.workstation', verbose_name='Рабочая станция')),
            ],
            options={
                'verbose_name_plural': 'Принтер',
                'ordering': ['employee', 'name'],
            },
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите должность', max_length=50, verbose_name='Должность')),
                ('departament', models.ForeignKey(blank=True, help_text='Введите название отдела', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.departament', verbose_name='Отдел')),
            ],
            options={
                'verbose_name_plural': 'Должность',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Выберете должность', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.post', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='employee',
            name='workplace',
            field=models.ForeignKey(blank=True, help_text='Выберете рабочее место', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.workplace', verbose_name='Рабочее место'),
        ),
        migrations.CreateModel(
            name='digitalSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Введите номер ключа', max_length=50, null=True, verbose_name='Ключ')),
                ('licenseKeyText', models.CharField(blank=True, help_text='Введите лицензионный ключ', max_length=50, null=True)),
                ('licenseKeyImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='OS/')),
                ('licenseKeyFile', models.FileField(blank=True, help_text='прикрепите файл', null=True, upload_to='soft/')),
                ('validityPeriod', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.employee', verbose_name='Сотрудник')),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.workplace', verbose_name='Рабочее место')),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.workstation', verbose_name='Рабочая станция')),
            ],
            options={
                'verbose_name_plural': 'ЭЦП',
                'ordering': ['validityPeriod'],
            },
        ),
    ]
