# Generated by Django 4.1.2 on 2022-10-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motherboard',
            old_name='COMPort',
            new_name='comPort',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='CPUSoket',
            new_name='cpuSoket',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='PCI',
            new_name='pci',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='RAMSlot',
            new_name='ramSlot',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='DispayPort',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='HDMI',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='PCI_E',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='SATA',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='USBPort',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='VGA',
        ),
        migrations.AddField(
            model_name='monitor',
            name='displayPort',
            field=models.CharField(blank=True, help_text='Укажите количество DisplayPort', max_length=50, null=True, verbose_name='количество DisplayPort'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='dpi',
            field=models.CharField(blank=True, help_text='Укажит плотность пикселей', max_length=50, null=True, verbose_name='Плотность пикселей'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='dvi',
            field=models.CharField(blank=True, help_text='Укажите количество DVI', max_length=50, null=True, verbose_name='количество DVI'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='frequency',
            field=models.CharField(blank=True, help_text='Укажите частоту', max_length=50, null=True, verbose_name='Частота'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='hdmi',
            field=models.CharField(blank=True, help_text='Укажите количество HDMI', max_length=50, null=True, verbose_name='количество HDMI'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='resolution',
            field=models.CharField(blank=True, help_text='Укажите разрешение', max_length=50, null=True, verbose_name='Разрешение'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='typeDisplay',
            field=models.CharField(blank=True, help_text='Укажите тип матрицы', max_length=50, null=True, verbose_name='Тип матрицы'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='usbPort',
            field=models.CharField(blank=True, help_text='Укажите количество USB', max_length=50, null=True, verbose_name='количество USB'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='vga',
            field=models.CharField(blank=True, help_text='Укажите количество VGA', max_length=50, null=True, verbose_name='количество VGA'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='dvi',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True, verbose_name='DVI'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='m2',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True, verbose_name='M2'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='pcie_x1',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True, verbose_name='PCIExpress X1'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='pcie_x16',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True, verbose_name='PCI Express X16'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='usb_2',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True, verbose_name='USB 2.0'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='usb_3',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True, verbose_name='USB 3.0'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='usb_3_1',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True, verbose_name='USB 3.1'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='usb_3_2',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True, verbose_name='USB 3.2'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='usb_4_0',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True, verbose_name='USB 4.0'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='invent',
            field=models.CharField(blank=True, help_text='Введите инвентарный номер', max_length=50, null=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='inventImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='monitor/invent/', verbose_name='Фото инвентарного номера'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='name',
            field=models.CharField(help_text='Введите название модели', max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='serial',
            field=models.CharField(blank=True, help_text='Введите серийный номер', max_length=50, null=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='serialImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='monitor/serial/', verbose_name='Фото серийного номера'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='invent',
            field=models.CharField(blank=True, help_text='Введите инвентарный номер', max_length=50, null=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='inventImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='motherboard/invent/', verbose_name='Фото инвентарного номера'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='name',
            field=models.CharField(help_text='Введите Название модели', max_length=50, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='serial',
            field=models.CharField(blank=True, help_text='Введите серийный номер', max_length=50, null=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='serialImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='motherboard/serial/', verbose_name='Фото серийного номера'),
        ),
        migrations.AlterField(
            model_name='os',
            name='licenseKeyText',
            field=models.CharField(blank=True, help_text='Введите лицензтонный ключ', max_length=50, null=True, verbose_name='Лицензионный ключ'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Укажите сотрудника', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='dispayPort',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True, verbose_name='DisplayPort'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='hdmi',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True, verbose_name='HDMI'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='sata',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True, verbose_name='SATA'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='vga',
            field=models.TextField(blank=True, help_text='Введите количество', max_length=200, null=True, verbose_name='VGA'),
        ),
    ]
