# Generated by Django 4.0.6 on 2022-10-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_employee_departament_alter_employee_workplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='name',
            field=models.CharField(help_text='Введите название отдела', max_length=50, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeEmail',
            field=models.EmailField(blank=True, help_text='Введие e-mail', max_length=254, null=True, unique=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='family',
            field=models.CharField(blank=True, help_text='Введите фамилию сотрудника', max_length=50, verbose_name='Фамилия сотрудника'),
        ),
        migrations.AlterField(
            model_name='post',
            name='departament',
            field=models.ForeignKey(blank=True, help_text='Введите название отдела', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.departament', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(help_text='Введите должность', max_length=50, verbose_name='Должность'),
        ),
    ]
