# Generated by Django 4.1.2 on 2022-10-27 05:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_comport_motherboard_comport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fotoval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название модели', max_length=50, verbose_name='Модель')),
                ('buhCode', models.CharField(help_text='Введите код по бухгалтерии', max_length=50, verbose_name='Код в бухгалтерии')),
                ('mileage', models.IntegerField(blank=True, help_text='Введите пробег', null=True, verbose_name='Пробег')),
                ('score', models.IntegerField(blank=True, help_text='Введите количество на складе', null=True, verbose_name='Остаток на складе')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name_plural': 'Фотовал',
            },
        ),
        migrations.CreateModel(
            name='toner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название модели', max_length=50, verbose_name='Модель')),
                ('buhCode', models.CharField(help_text='Введите код по бухгалтерии', max_length=50, verbose_name='Код в бухгалтерии')),
                ('score', models.IntegerField(blank=True, help_text='Введите количество на складе', null=True, verbose_name='Остаток на складе')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name_plural': 'Тонер',
            },
        ),
        migrations.AlterModelOptions(
            name='cartridge',
            options={'verbose_name_plural': 'Картридж'},
        ),
        migrations.AlterModelOptions(
            name='printer',
            options={'ordering': ['name'], 'verbose_name_plural': 'Принтер'},
        ),
        migrations.RenameField(
            model_name='printer',
            old_name='LANPort',
            new_name='lanPort',
        ),
        migrations.RenameField(
            model_name='printer',
            old_name='USBPort',
            new_name='usbPort',
        ),
        migrations.RemoveField(
            model_name='cartridge',
            name='manufactured',
        ),
        migrations.RemoveField(
            model_name='cartridge',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='cartridge',
            name='serialImg',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='manufactured',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='workstation',
        ),
        migrations.AddField(
            model_name='cartridge',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='printer',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='printer',
            name='score',
            field=models.IntegerField(blank=True, help_text='Введите количество на складе', null=True, verbose_name='Остаток на складе'),
        ),
        migrations.AddField(
            model_name='printer',
            name='tray1',
            field=models.TextField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2'), ('A1', 'A1'), ('A0', 'A0'), ('A5', 'A5'), ('Конверт', 'Конверт'), ('Отсутствует', 'Отсутствует')], default='A4', help_text='Укажите формат бумаги', max_length=15, verbose_name='Лоток №1 для подачи бумаги'),
        ),
        migrations.AddField(
            model_name='printer',
            name='tray2',
            field=models.TextField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2'), ('A1', 'A1'), ('A0', 'A0'), ('A5', 'A5'), ('Конверт', 'Конверт'), ('Отсутствует', 'Отсутствует')], default='A3', help_text='Укажите формат бумаги', max_length=15, verbose_name='Лоток №2 для подачи бумаги'),
        ),
        migrations.AddField(
            model_name='printer',
            name='tray3',
            field=models.TextField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2'), ('A1', 'A1'), ('A0', 'A0'), ('A5', 'A5'), ('Конверт', 'Конверт'), ('Отсутствует', 'Отсутствует')], default='Отсутствует', help_text='Укажите формат бумаги', max_length=15, verbose_name='Лоток №3 для подачи бумаги'),
        ),
        migrations.AddField(
            model_name='printer',
            name='traySide',
            field=models.TextField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2'), ('A1', 'A1'), ('A0', 'A0'), ('A5', 'A5'), ('Конверт', 'Конверт'), ('Отсутствует', 'Отсутствует')], default='A4', help_text='Укажите формат бумаги', max_length=15, verbose_name='Боковой для подачи бумаги'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='cartridge',
            field=models.ForeignKey(blank=True, help_text='Укажите картридж', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cartridge', verbose_name='Картридж'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='invent',
            field=models.CharField(blank=True, help_text='Введите инвентарный номер', max_length=50, null=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='inventImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='printer/invent/', verbose_name='Фото инвентарного номера'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(blank=True, help_text='Введите модель принтера', max_length=50, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='serialImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='printer/serial/', verbose_name='Фото серийного номера'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='workplace',
            field=models.ForeignKey(blank=True, help_text='Укажите рабочее место', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.workplace', verbose_name='Рабочее место'),
        ),
        migrations.DeleteModel(
            name='paper',
        ),
        migrations.AddField(
            model_name='printer',
            name='fotoval',
            field=models.ForeignKey(blank=True, help_text='Укажите фотовал', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.fotoval', verbose_name='Фотовал'),
        ),
        migrations.AddField(
            model_name='printer',
            name='toner',
            field=models.ForeignKey(blank=True, help_text='Укажите тонер', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.toner', verbose_name='Тонер'),
        ),
    ]
