# Generated by Django 4.1.2 on 2022-10-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_fotoval_toner_alter_cartridge_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='modelPrinter',
            field=models.CharField(blank=True, help_text='Введите модель принтера', max_length=50, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(blank=True, help_text='Введите название принтера', max_length=50, null=True, verbose_name='Название'),
        ),
    ]
