# Generated by Django 4.1.2 on 2022-10-28 05:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_printer_modelprinter_alter_printer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Введите номер ключа', max_length=50, null=True, verbose_name='Ключ')),
                ('licenseKeyFileOpen', models.FileField(blank=True, help_text='Прикрепите файл', null=True, upload_to='soft/Open/', verbose_name='Открытая часть лицензии')),
                ('licenseKeyFileClose', models.FileField(blank=True, help_text='Прикрепите файл', null=True, upload_to='soft/Close/', verbose_name='Закрытая часть лицензии')),
                ('periodOpen', models.DateField(blank=True, help_text='Укажите дату', null=True, verbose_name='Срок действия открытой части')),
                ('periodClose', models.DateField(blank=True, help_text='Укажите дату', null=True, verbose_name='Срок действия закрытой части')),
                ('employeeRegister', models.ForeignKey(blank=True, help_text='Укажите сотрудника', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.employee', verbose_name='Сотрудник на которого оформлена ЭЦП')),
                ('employeeStorage', models.ForeignKey(blank=True, help_text='Укажите сотрудника', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.employee', verbose_name='Сотрудник у которого хранится ЭЦП')),
            ],
            options={
                'verbose_name_plural': 'ЭЦП',
                'ordering': ['periodOpen', 'periodClose'],
            },
        ),
        migrations.CreateModel(
            name='storage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите номер станции', max_length=50, verbose_name='Рабочая станция')),
                ('modelStorage', models.CharField(blank=True, help_text='Введите название модели', max_length=200, null=True, verbose_name='Модель')),
                ('serial', models.CharField(blank=True, help_text='Введите серийный номер', max_length=50, null=True, verbose_name='Серийный номер')),
                ('serialImg', models.ImageField(blank=True, help_text='Прикрепите файл', null=True, upload_to='storage/serial/', verbose_name='Фото серийного номера')),
                ('invent', models.CharField(blank=True, help_text='Введите инвентаризационный номер', max_length=50, null=True, verbose_name='Инвентарный номер')),
                ('inventImg', models.ImageField(blank=True, help_text='Прикрепите файл', null=True, upload_to='storage/invent/', verbose_name='Фото инвентарного номера')),
                ('plug', models.TextField(blank=True, help_text='Укажите тип подключения', max_length=20, null=True, verbose_name='Тип подключения')),
                ('typeMemory', models.TextField(blank=True, help_text='Укажите тип памяти', max_length=200, null=True, verbose_name='Тип памяти')),
                ('volumeMemory', models.TextField(blank=True, help_text='Укажите объем памяти', max_length=200, null=True, verbose_name='Объем памяти')),
                ('employee', models.ForeignKey(blank=True, help_text='Укажите сотрудника', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.employee', verbose_name='Сотрудник')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name_plural': 'Накопитель',
                'ordering': ['employee', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='printer',
            name='traySide',
            field=models.TextField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2'), ('A1', 'A1'), ('A0', 'A0'), ('A5', 'A5'), ('Конверт', 'Конверт'), ('Отсутствует', 'Отсутствует')], default='A4', help_text='Укажите формат бумаги', max_length=15, verbose_name='Боковой лоток для подачи бумаги'),
        ),
        migrations.DeleteModel(
            name='digitalSignature',
        ),
        migrations.AddField(
            model_name='signature',
            name='storage',
            field=models.ForeignKey(blank=True, help_text='Укажите накопитель', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.storage', verbose_name='накопитель'),
        ),
        migrations.AddField(
            model_name='signature',
            name='workstation',
            field=models.ForeignKey(blank=True, help_text='Укажите рабочую станцию', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.workstation', verbose_name='Рабочая станция'),
        ),
    ]
