# Generated by Django 4.1.2 on 2022-10-31 05:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_monitor_displayport_alter_monitor_dpi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='inventImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='cpu/invent/', verbose_name='Фото инвентарного номера'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='serialImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='cpu/serial/', verbose_name='Фото серийного номера'),
        ),
        migrations.CreateModel(
            name='gpu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название модели', max_length=50, verbose_name='Модель')),
                ('type', models.CharField(choices=[('Интегрированная', 'Интегрированная'), ('Дискретная', 'Дискретная')], help_text='Введите название модели', max_length=50, verbose_name='Модель')),
                ('serial', models.CharField(blank=True, help_text='Введите серийный номер', max_length=50, null=True, verbose_name='Серийный номер')),
                ('serialImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='cpu/serial/', verbose_name='Фото серийного номера')),
                ('invent', models.CharField(blank=True, help_text='Введите инвентарный номер', max_length=50, null=True, verbose_name='Инвентарный номер')),
                ('inventImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='cpu/invent/', verbose_name='Фото инвентарного номера')),
                ('gram', models.CharField(blank=True, help_text='Укажите объем памяти', max_length=50, null=True, verbose_name='Объем памяти')),
                ('gramType', models.CharField(blank=True, help_text='Укажите тип памяти', max_length=50, null=True, verbose_name='Тип памяти')),
                ('pcie', models.CharField(blank=True, help_text='Укажите версию PCI Express', max_length=50, null=True, verbose_name='Версия PCI Express')),
                ('supply', models.CharField(blank=True, help_text='Укажите тип питания', max_length=50, null=True, verbose_name='Питание')),
                ('score', models.IntegerField(blank=True, help_text='Введите количество на складе', null=True, verbose_name='Остаток на складе')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name_plural': 'GPU',
            },
        ),
        migrations.AlterField(
            model_name='workstation',
            name='gpu',
            field=models.ForeignKey(blank=True, help_text='Укажите GPU', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.gpu', verbose_name='GPU'),
        ),
    ]
