# Generated by Django 4.1.2 on 2022-10-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_cpu_inventimg_alter_cpu_serialimg_gpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='inventImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='gpu/invent/', verbose_name='Фото инвентарного номера'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='serialImg',
            field=models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='gpu/serial/', verbose_name='Фото серийного номера'),
        ),
    ]
