# Generated by Django 4.1 on 2023-01-11 06:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Введите номер кабинета', max_length=15, verbose_name='Кабинет')),
                ('building', models.CharField(blank=True, help_text='Введите название здания', max_length=25, verbose_name='Здание')),
                ('floor', models.CharField(blank=True, help_text='Введите номер этажа', max_length=25, verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='workplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите номер рабочего места', max_length=50, verbose_name='Рабочее место')),
                ('room', models.ForeignKey(blank=True, help_text='Выберете номер кабинета', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workplace.room', verbose_name='Номер кабинета')),
            ],
            options={
                'verbose_name': 'Рабочее место',
                'verbose_name_plural': 'Рабочие места',
                'ordering': ['room'],
            },
        ),
    ]
