# Generated by Django 4.1 on 2023-01-11 16:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_remove_os_manufacturer_remove_software_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='software',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название ПО', max_length=50, verbose_name='Програмное обеспечение')),
                ('version', models.CharField(blank=True, help_text='Укажите версию', max_length=200, null=True, verbose_name='Версия')),
                ('bitDepth', models.CharField(blank=True, help_text='Укажите разрядность', max_length=200, null=True, verbose_name='разрядность')),
                ('licenseKeyText', models.CharField(blank=True, help_text='Введите лицензтонный ключ', max_length=50, null=True, verbose_name='Введите ключ')),
                ('licenseKeyImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='software/soft/', verbose_name='Фото ключа')),
                ('licenseKeyFile', models.FileField(blank=True, help_text='прикрепите файл', null=True, upload_to='software/soft/', verbose_name='Файл лицензии')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Програмное обеспечение',
                'verbose_name_plural': 'Програмное обеспечение',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='os',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите название ОС', max_length=50, verbose_name='Операционная система')),
                ('version', models.CharField(blank=True, help_text='Укажите версию', max_length=200, null=True, verbose_name='Версия')),
                ('bitDepth', models.CharField(blank=True, help_text='Укажите разрядность', max_length=200, null=True, verbose_name='разрядность')),
                ('licenseKeyText', models.CharField(blank=True, help_text='Введите лицензтонный ключ', max_length=50, null=True, verbose_name='Лицензионный ключ')),
                ('licenseKeyImg', models.ImageField(blank=True, help_text='прикрепите файл', null=True, upload_to='software/OS/', verbose_name='Фото ключа')),
                ('licenseKeyFile', models.FileField(blank=True, help_text='прикрепите файл', null=True, upload_to='software/OS/', verbose_name='Файл лицензии')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Укажите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Операционная система',
                'verbose_name_plural': 'Операционные системы',
            },
        ),
    ]
