name: Django Actions

on:
  push:
    branch: [backend]
  pull_request:
    branch: [master]

jobs:
  integration-tests:
    # На какой ОС будет работать виртуальная машина
    # Можно выбрать Ubuntu, Windows Server или macOS
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./backend/docker-compose.yaml"
        env:
          DEBUG: 1
          SECRET_KEY: foo
          DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
          SQL_ENGINE: django.db.backends.postgresql
          SQL_DATABASE: test_base
          SQL_USER: test_admin
          SQL_PASSWORD: zx23SA21
          SQL_HOST: db
          SQL_PORT: 5432
          SQL_PGDATA: "/var/lib/postgresql/data/pgdata"
          POSTGRES_USER: test_admin
          POSTGRES_PASSWORD: zx23SA21
          POSTGRES_DB: test_base
          PGDATA: "/var/lib/postgresql/data/pgdata"
          CELERY_BROKER: redis://redis:6379/0
          CELERY_BACKEND: redis://redis:6379/0
      - name: Check types backend
        run: docker exec backend pdm run mypy .
      - name: Linting backend
        run: docker exec backend pdm run ruff check .
      - name: Run tests
        run: docker exec backend pdm run pytest --cov
