name: test_project  
on:
  # activates the workflow when there is a push or pull request on the main branch
  push:
    branches: [ work-branch ]
  pull_request:
    branches: [ master ]
jobs:  
  test_project: 
# the operating system your job will run on
     runs-on: ubuntu-latest  
     steps:  
       - uses: actions/checkout@v2  
       - uses: actions/setup-python@v2  
       - run: pip install -r requirements.txt  # install requirements to enable GitHub run our code
       - run: pytest . # run the unit test
