name: Django Actions

on: 
  push:
    branch: [work-branch]
  pull_request:
    branch: [master]

jobs:
  integration-tests:
    # На какой ОС будет работать виртуальная машина
    # Можно выбрать Ubuntu, Windows Server или macOS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
        env:
          DEBUG: 1
          SECRET_KEY: foo
          DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
          SQL_ENGINE: django.db.backends.postgresql
          SQL_DATABASE: buildAndTech
          SQL_USER: adminDevelop
          SQL_PASSWORD: zx23SA21
          SQL_HOST: db
          SQL_PORT: 5432
          CELERY_BROKER: redis://redis:6379/0
          CELERY_BACKEND: redis://redis:6379/0
      - name: Run migrations
        run: docker-compose exec -T web python3 manage.py makemigrations
      - name: Run migrate
        run: docker-compose exec -T web python3 manage.py migrate
      - name: Run tests
        run: docker-compose exec -T web pytest -n 4
      - name: Stop conteiners
        run: docker-compose down -v